repos:
    - repo: local
      hooks:
          - id: prettier
            name: format with prettier
            language: system
            entry: prettier.cmd --tab-width=4 --trailing-comma="all" --print-width=120 -u --write
